/* Generated by Together */

package com.servicefoundry.books.webservices.models.businessobject;

public class BusinessObjectCollection {
    public BusinessObjectKey create(BusinessObject obj) {
    }

    public BusinessObject read(BusinessObjectKey key) {
    }

    public void update(BusinessObjectKey key, BusinessObject obj) {
    }

    public void delete(BusinessObjectKey key) {
    }

    public BusinessObject get(BusinessObjectKey p0){}

    /**
     * @link aggregation
     * @clientCardinality 1
     * @supplierCardinality 0..* 
     */
    private BusinessObject lnkBusinessObject;
}
