/* Generated by Together */

package com.servicefoundry.books.webservices.models.businessobject;

public class ComplexData {
    public PrimitiveData getPrimitiveData() {
    }

    public void setComplexData() {
    }

    public ComplexData getComplexData() {
    }

    public void setPrimitiveData(PrimitiveType arg) {
    }

    private PrimitiveType property;

    /**
     * @link aggregationByValue
     * @supplierCardinality 0..*
     * @clientCardinality 1 
     */
    private ComplexData lnkComplexData;
}
