/* Generated by Together */

package com.servicefoundry.books.webservices.models.servicetoapp;

public class ImplementationClassProxy implements ImplementationClass {
    public void operation() {
    }
}
