/* Generated by Together */

package com.servicefoundry.books.webservices.models.servicetoapp;

import java.rmi.server.UnicastRemoteObject;
public class ImplementationClassImpl extends UnicastRemoteObject implements ImplementationClass {
    public void operation() {
    }
}
