/* Generated by Together */

package com.servicefoundry.books.webservices.models.servicetoapp;

public class ServiceImplementation {
    public void operation() {
    }

    /**
     * @supplierCardinality 1
     * @clientCardinality 0..*
     * @directed 
     */
    private ImplementationClassProxy lnkImplementationClass;
}
