/* Generated by Together */

package com.servicefoundry.books.webservices.models.observer;

import java.util.Vector;
import java.util.Observable;

/**
 * @stereotype service implementation 
 */
public class ConcreteObservable implements com.servicefoundry.books.webservices.models.observer.Observable {
    public void addObserver(String location){ }

    public void removeObserver(String location){ }

    public void notify(){}

    /**
     * @directed
     * @clientCardinality 0..*
     * @supplierCardinality 0..* 
     */
    private Observer lnkObserver;
}
