/* Generated by Together */

package com.servicefoundry.books.webservices.models.observer;

import java.util.Observer;

/**
 * @stereotype service implementation 
 */
public class ConcreteObserver implements com.servicefoundry.books.webservices.models.observer.Observer {
    public void ConcreteObserver(){}

    public void update(){ }
}
