/* Generated by Together */

package com.servicefoundry.books.webservices.models.observer;

import java.util.Observer;
import java.util.Observable;
public class JavaObserver implements Observer {
    public void update(Observable par1, Object par2){ }
}
