/* Generated by Together */

package architecture;

public class ArchitectureAComponent {
    /**
     * @label Architecture A communication style 
     */
    private ArchitectureAdapter lnkArchitectureAdapter;

    /**
     * @label Architecture A communication style 
     */
    private ClientAdapterA lnkClientAdapterA;
}
