/* Generated by Together */

package architecture;

public class ArchitectureAdapter {
    /**
     * @label Architecture B communication style 
     */
    private ArchitectureBComponent lnkArchitectureBComponent;
}
