/* Generated by Together */

package architecture;

public class ClientAdapterA {
    public void operationACallStyle(){}

    /**
     * @label Private communication style 
     */
    private ClientAdapterB lnkClientAdapterB;
}
