/* Generated by Together */

package architecture;

public class ClientAdapterB {
    public void operationPrivateCallStyle(){}

    /**
     * @label Architecture B communication style 
     */
    private ArchitectureBComponent lnkArchitectureBComponent;
}
