/* Generated by Together */

package architecture;

/**
 * @stereotype tier 
 */
public class Middle {
    /**
     * @directed
     * @link aggregationByValue 
     */
    private EJB_Container lnkEJB_Container;

    /**
     * @directed
     * @link aggregationByValue 
     */
    private Web_Container lnkWeb_Container;
    private Enterprise_Information_Services lnkEnterprise_Information_Services;
}
