/* Generated by Together */

package architecture;

public class Service {
    public void operation(){}

    /**
     * @label publish
     * @directed 
     */
    private Directory lnkDirectory;
}
