/* Generated by Together */

package architecture;

/**
 * @stereotype web tier 
 */
public class Tomcat {
    /**
     * @label component route 
     */
    private Axis_Engine lnkAxis_Engine;

    /**
     * @label presentation route 
     */
    private Front_Controller lnkFront_Controller;
}
