/* Generated by Together */

package com.servicefoundry.books.webservices.models.partialpopulation;

import com.servicefoundry.books.webservices.models.datatransferobject.DataTransferObject;
public class BusinessObject {
    public void setDataTransferObject(DataTransferObject p0) {
    }

    public DataTransferObject getDataTransferObject() {
    }

    public Object getValue1() {
    }

    public void setValue1(Value p0){}

    public void setValue2() {
    }

    public Object getValue2() {
    }

    /**
     * @label create or consume
     * @directed 
     */
    private DataTransferObject lnkDataTransferObject;

    /**
     * @directed
     * @label create or consume 
     */
    private com.servicefoundry.books.webservices.models.partialpopulation.DataTransferObject lnkDataTransferObject1;
}
