/* Generated by Together */

package com.servicefoundry.books.webservices.models.partialpopulation;

import com.servicefoundry.books.webservices.models.datatransferobject.DataTransferCollection;
public class BusinessObjectCollection {
    public DataTransferCollection getDataTransferObjects() {
    }

    public void setDataTransferObjects() {
    }

    /**
     * @directed
     * @label create or consume 
     */
    private DataTransferCollection lnkDataTransferCollection;

    /**
     * @directed
     * @label create or consume 
     */
    private com.servicefoundry.books.webservices.models.partialpopulation.DataTransferCollection lnkDataTransferCollection1;
}
