/* Generated by Together */

package com.servicefoundry.books.webservices.models.partialpopulation;

import com.servicefoundry.books.webservices.models.datatransferobject.DataTransferObject;
import com.servicefoundry.books.webservices.models.datatransferobject.DataTransferCollection;
 public class Client {
    /**
     * @label create or consume
     * @directed 
     */
    private com.servicefoundry.books.webservices.models.partialpopulation.DataTransferObject lnkDataTransferObject;

    /**
     * @directed
     * @label create or consume 
     */
    private com.servicefoundry.books.webservices.models.partialpopulation.DataTransferCollection lnkDataTransferCollection;
}
