/* Generated by Together */

package com.servicefoundry.books.webservices.models.partialpopulation;

public class DataTransferObject {
    public Object getValue1() {
    }

    public void setValue2() {
    }

    public void setValue1() {
    }

    public Object getValue2() {
    }
}
