/* Generated by Together */

package com.servicefoundry.books.webservices.models.partialpopulation;

import com.servicefoundry.books.webservices.models.datatransferobject.DataTransferObject;
public class DataTransferCollection {
    public DataTransferObject[] getDataTransferObjects() {
    }

    public void setDataTransferObjects() {
    }

    /**
     * @directed
     * @supplierCardinality 0..*
     * @clientCardinality 1
     * @link aggregation 
     */
    private com.servicefoundry.books.webservices.models.partialpopulation.DataTransferObject lnkDataTransferObject;
}
