/* Generated by Together */

package com.servicefoundry.books.webservices.models.datatransferobject;

public class BusinessObject {
    public void setDataTransferObject(DataTransferObject dto) {
    }

    public DataTransferObject getDataTransferObject() {
    }

    /**
     * @label create or consume
     * @directed 
     */
    private DataTransferObject lnkDataTransferObject;
}
