/* Generated by Together */

package com.servicefoundry.books.webservices.models.datatransferobject;

public class BusinessObjectCollection {
    public DataTransferCollection getDataTransferObjects() {
    }

    public void setDataTransferObjects() {
    }

    /**
     * @directed
     * @label create or consume 
     */
    private DataTransferCollection lnkDataTransferCollection;
}
