/* Generated by Together */

package com.servicefoundry.books.webservices.models.datatransferobject;

public class Client {
    /**
     * @label create or consume
     * @directed 
     */
    private DataTransferObject lnkDataTransferObject;

    /**
     * @directed
     * @label create or consume 
     */
    private DataTransferCollection lnkDataTransferCollection;
}
