/* Generated by Together */

package com.servicefoundry.books.webservices.models.datatransferobject;

public class DataTransferCollection {
    /**
     * @directed
     * @supplierCardinality 0..*
     * @clientCardinality 1
     * @link aggregation 
     */
    private DataTransferObject lnkDataTransferObject;
}
