/* Generated by Together */

package com.servicefoundry.books.webservices.models.BusinessProcess;

import java.util.LinkedList;
public class ActivitySequence extends LinkedList {
    public BusinessActivity next() {
    }

    public BusinessActivity get() {
    }

    /**
     * @link aggregationByValue
     * @clientCardinality 1
     * @supplierCardinality 1
     * @directed 
     */
    private Data lnkData;

    /**
     * @clientCardinality 0..*
     * @supplierCardinality 0..*
     * @link aggregation
     * @directed 
     */
    private BusinessActivity lnkBusinessActivity;
}
