/* Generated by Together */

package com.servicefoundry.books.webservices.models.BusinessProcess;

public class BPEL_Container {
    public void invoke() {
    }
    public void receive() {}
    public void reply(){}
    public void wait(){}
    public void terminate(){}
    public void sequence(){}
    public void pick(){}
    public void flow(){}
}
