/* Generated by Together */

package com.servicefoundry.books.webservices.models.BusinessProcess;

public class BusinessProcessImpl implements BusinessProcess {
    public void start() {
    }

    /**
     * @link aggregationByValue
     * @directed
     * @clientCardinality 1
     * @supplierCardinality 1 
     */
    private ActivitySequence lnkActivitySequence;
}
