/* Generated by Together */

package com.servicefoundry.books.webservices.models.BusinessProcess;

public class Web_Service {
    public void businessProcess() {
    }

    private BPEL_Container lnkBPEL_Container;
}
