/* Generated by Together */

package com.servicefoundry.books.webservices.models.servicedirectory;

public class Application {
    public void createArchitectureAdapter(){}

    /**
     * @directed 
     */
    private Directory lnkDirectory;
}
