/* Generated by Together */

package com.servicefoundry.books.webservices.models.servicedirectory;

public class BindingTemplate {
    /**
     * @clientCardinality 0..*
     * @supplierCardinality 0..* 
     */
    private BusinessService lnkBusinessService;

    /**
     * @clientCardinality 0..*
     * @supplierCardinality 0..* 
     */
    private TechnicalModel lnkTechnicalModel;
}
