/* Generated by Together */

package com.servicefoundry.books.webservices.models.servicedirectory;

public class BusinessEntity {
    /**
     * @clientCardinality 1
     * @supplierCardinality 0..*
     * @directed
     * @link aggregationByValue 
     */
    private Contact lnkContact;

    /**
     * @clientCardinality 1
     * @link aggregationByValue
     * @directed
     * @supplierCardinality 0..* 
     */
    private BusinessService lnkBusinessService;
}
