/* Generated by Together */

package com.servicefoundry.books.webservices.models.servicedirectory;

public class Directory {
    public void publish() {
    }

    public void delete() {
    }

    public ServiceInformation locate() {
    }

    public void register() {
    }

    public void update() {
    }

    /**
     * @directed 
     */
    private ServiceInformation lnkServiceInformation;
}
