/* Generated by Together */

package com.servicefoundry.books.webservices.models.servicedirectory;

public class ServiceInformation {
    public void getInformation(){}

    /**
     * @directed
     * @label refers to 
     */
    private ServiceImplementation lnkDirectory;
}
