/* Generated by Together */

package com.servicefoundry.books.webservices.models.pubsub;

public interface EventService {
    void addSubscriber(String topic, String subscriptionUrl);

    void removeSubscriber(String topic, String subscriptionUrl);

    void publish(String topic, String data);
}
