/* Generated by Together */

package com.servicefoundry.books.webservices.models.fauximplementation;

public class Client {
    /**
     * @label uses
     * @directed 
     */
    private ClassInterface lnkClassInterface;
}
