/* Generated by Together */

package com.servicefoundry.books.webservices.models.servicefactory;

public class Application {
    /**
     * @directed 
     */
    private Service lnkService;

    /**
     * @directed 
     */
    private ClassInterface lnkClassInterface;

    /**
     * @directed 
     */
    private ServiceFactory lnkServiceFactory;

    /**
     * @directed 
     */
    private ClassFactory lnkClassFactory;
}
