/* Generated by Together */

package com.servicefoundry.books.webservices.models.servicefactory;

public class ClassFactory {
    public ClassInterface getInstance() {
    }

    protected ClassInterface findObject() {
    }

    /**
     * @directed 
     */
    private ClassInterface lnkClassInterface;
}
