/* Generated by Together */

package com.servicefoundry.books.webservices.models.servicefactory;

public class ClassImplA {
    /**
     * @directed 
     */
    private ClassInterface lnkClassInterface;
}
