/* Generated by Together */

package com.servicefoundry.books.webservices.models.servicefactory;

public class Directory {
    public void lookup(){}

    /**
     * @directed 
     */
    private ServiceImplA lnkServiceImplA;

    /**
     * @directed 
     */
    private ServiceImplB lnkServiceImplB;
}
