/* Generated by Together */

package com.servicefoundry.books.webservices.models.servicefactory;

public class ServiceFactory {
    public Service getService() {
    }

    /**
     * @label uses
     * @directed 
     */
    private Directory lnkDirectory;

    /**
     * @directed 
     */
    private Service lnkService;
}
