/* Generated by Together */

package com.servicefoundry.books.webservices.models.asynchbusinessprocess;

public class BusinessProcessManager {
    public Object getAttribute(String id) {
    }

    public String startProcess() {
    }

    private BusinessProcess lnkBusinessProcess;

    /**
     * @link aggregationByValue 
     */
    private ProcessState lnkProcessState;
}
