/* Generated by Together */

package com.servicefoundry.books.webservices.models.asynchbusinessprocess;

import com.servicefoundry.books.webservices.patterns.BusinessProcess.BusinessActivity;
public class BusinessActivityImpl implements com.servicefoundry.books.webservices.patterns.asynchbusinessprocess.BusinessActivity {
    public void start(){ }
}
