/* Generated by Together */

package com.servicefoundry.books.webservices.models.asynchbusinessprocess;

import com.servicefoundry.books.webservices.patterns.BusinessProcess.BusinessProcess;
import com.servicefoundry.books.webservices.patterns.BusinessProcess.ActivitySequence;
public class BusinessProcessImpl implements com.servicefoundry.books.webservices.patterns.asynchbusinessprocess.BusinessProcess {
    public void start() {
    }

    /**
     * @link aggregationByValue
     * @directed
     * @clientCardinality 1
     * @supplierCardinality 1 
     */
    private com.servicefoundry.books.webservices.patterns.asynchbusinessprocess.ActivitySequence lnkActivitySequence;
}
