/* Generated by Together */

package com.servicefoundry.books.webservices.models.asynchbusinessprocess;

import com.servicefoundry.books.webservices.patterns.BusinessProcess.BusinessActivity;

/**
 * @stereotype pattern 
 */
public interface BusinessProcess {
    void start();
}
