/* Generated by Together */

package com.servicefoundry.books.webservices.models.asynchbusinessprocess;

public class ProcessState {
    public Object getAttribute(String id) {
    }

    public void setAttribute(String id, Object value) {
    }
}
